site_name: Software Documentation

repo_name: 'SoftwareDocumentation'
repo_url: 'https://github.com/fellipe-araujo/SoftwareDocumentation'

copyright: 'Copyright &copy; 2020 Software Documentation'

theme: material

nav:
  - Início: index.md
  - Documentos de Software:
    - Documento de Arquitetura: DocSoftware/doc_architecture.md
    - Documento de Visão: DocSoftware/doc_vision.md
  - Diagramas:
    - Diagrama de Classe: Diagrams/class_diagram.md
    - Diagrama de Pacotes: Diagrams/package_diagram.md
  - Banco de Dados:
    - ME-R: DocDatabase/mer.md
    - DE-R: DocDatabase/der.md
    - DLD: DocDatabase/dld.md
  - Políticas:
    - Banches: Policies/branch.md
    - Commits: Policies/commit.md
    - Issues: Policies/issue.md
    - PRs: Policies/pr.md